baseURL: https://electrodynamics.yktoo.com
languageCode: ru-ru
defaultContentLanguage: ru
title: "Электродинамика: взгляд физика"

markup:
  goldmark:
    renderer:
      # Enable inline HTML
      unsafe: true

disableKinds:
  - taxonomy
  - term

services:
  googleAnalytics:
    id: 'G-YBMK7NDJ5K'

module:
  hugoVersion:
    extended: true
    min: "0.150.0"
  mounts:
    - source: node_modules
      target: assets/node_modules
    - source: assets
      target: assets
    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
    - source: static
      target: static

params:
  author: К. Б. Канн
  description: >
    Виртуальный мемориал доктора технических наук, профессора Константина Борисовича Канна (23.04.1936 — 28.12.2020).
    Изложение его видения современного состояния электродинамики, а также несостыковок и проблем, требующих дальнейших исследований и объяснений.
  keywords:
    - вихревое поле
    - гармонические индукционные процессы
    - гармонический индукционный электрогенератор
    - диск Фарадея
    - закон Ома
    - законы электромагнитной индукции
    - И.Е.Тамм
    - индукция
    - Ленц
    - магнетизм
    - магнитное поле
    - магнитный поток
    - Максвелл
    - парадокс Геринга
    - парадоксы физики
    - парадоксы электромагнитной индукции
    - сила Лоренца
    - современное состояние физики
    - стационарное поле
    - структура магнитного поля
    - Фарадей
    - физика
    - ЭДС
    - электрический заряд
    - электрический ток
    - электрическое поле
    - электродинамика
    - электромагнетизм
    - электромагнитная индукция
    - электромагнитные волны
    - электроэнергия
  comentario:
    scriptUrl: https://comentario.app/comentario.js
    siteId: 87d7f33f-3065-4c7d-a02f-e0a25373b389
